### ISSUE TITLE
第12个webshell请教

### ISSUE THREAD

**Issue by m0w3n** [threedr3am/JSP-Webshells#1]
三梦师傅好，我在研究你的jsp-webshells，第12个运行的时候报“java.lang.ClassNotFoundException: XXXX”错误，Java小白，不知道要怎么改，希望师傅不吝赐教！

**Comment by threedr3am** [comment]
你执行一下
```
javac Threedr3am_12.java

cat Threedr3am_12.class|base64
```
然后把base64编码的字节码替换一下12.jsp里面的base64字节码试试

**Comment by Little-kwy** [comment]
> 你执行一下
> 
> ```
> javac Threedr3am_12.java
> 
> cat Threedr3am_12.class|base64
> ```
> 
> 然后把base64编码的字节码替换一下12.jsp里面的base64字节码试试

感谢，12已经解决了，能否问下师傅18中的base64的字节码是不是有问题？有一个无效的Constant Type为118（我是在java 1.8.0_181的环境中），或者师傅能否给下Threedr3amScript2.java，非常感谢！
